import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer/footer";
import Header from "../components/Header/header";
import logo from "../public/images/logo.png";
import logo1 from "../public/images/logo copy.png";
import logo2 from "../public/images/logo copy 2.png";
import styles from "../styles/pages.module.scss";
import { Carousel } from "react-bootstrap";
import { getAllProductIds, db } from "../hooks/firebase/firebase";
import { collection, addDoc } from "firebase/firestore";

type PathsType = {
	params: [
		{
			id: string;
		}
	];
};

async function Paths() {
	const paths = await getAllProductIds();
	console.log("paths ", paths);
}

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<button type="button" onClick={getAllProductIds}>
				All Ids
			</button>
			<button type="button" onClick={Paths}>
				All Paths
			</button>

			<Header></Header>

			<main>
				<section className="container">
					<div className="row ">
						<div className="col-12">
							<Carousel>
								<Carousel.Item>
									<Image className="d-block" width="1000px" height="500px" src={logo} alt="First slide" />
									<Carousel.Caption>
										<h3>First slide label</h3>
										<p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
									</Carousel.Caption>
								</Carousel.Item>
								<Carousel.Item>
									<Image className="d-block" width="1000px" height="500px" src={logo} alt="Second slide" />

									<Carousel.Caption>
										<h3 className="btn-alert">Second slide label</h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
									</Carousel.Caption>
								</Carousel.Item>
								<Carousel.Item>
									<Image className="d-block" width="1000px" height="500px" src={logo} alt="Third slide" />

									<Carousel.Caption>
										<h3>Third slide label</h3>
										<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
									</Carousel.Caption>
								</Carousel.Item>
							</Carousel>
						</div>
					</div>
				</section>
			</main>

			<Footer></Footer>
		</>
	);
};

export default Home;
